# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Angelo Mesh
tagline:          'A Meshtastic group'
description:      'A group of radio enthusiasts bringing decentralized communication to San Angelo.'
url:              http://angelomesh.com
baseurl:          /angelomesh

paginate:         5