# Dependencies
markdown:         kramdown
highlighter:      rouge

url:              http://angelomesh.com/
baseurl:          /

# Permalinks
permalink:        pretty

author:
  name:           'Christian Thompson'
  email:          'luca@urbanforest.dev'

# Setup
title:            'Angelo Mesh'
tagline:          'A Meshtastic group'
description:      'A group of radio enthusiasts bringing decentralized communication to San Angelo.'

paginate:         5