# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Angelo Mesh
tagline:          'A Jekyll theme'
description:      'A group of radio enthusiasts bringing decentralized communication to San Angelo.'
url:              http://angelomesh.com
baseurl:          /

paginate:         5